# Generated by Django 3.2.16 on 2022-12-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('cityName', models.CharField(max_length=50, verbose_name='City name')),
                ('temperature', models.CharField(max_length=50, verbose_name='temperature')),
                ('feels_like_temperature', models.CharField(max_length=50, verbose_name='feels_like temperature')),
                ('sky', models.CharField(max_length=50, verbose_name='sky')),
                ('time', models.DateTimeField()),
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
